### ISSUE TITLE
News card image is wrong

### ISSUE THREAD

**Issue by Elendan** [Elendan/launcher-bug-report#2]
**Bug Information**

- Images for the news is wrong. It's always the same image as if they weren't fetched from database. It would be a great fallback image in case there is no link in database though

**Screenshots**
![image](https://i.gyazo.com/8575c2305dbe51f538c7e89ffe63371c.png)

**Comment by maddoctor1905** [comment]
@Elendan 
We can't fetch your images from your website due to cloudflare's DDOS protection.
When i fetch https://nosbyte.eu/assets/images/home/example.jpg, cloudflare block me with an html page. Therefore i cant get the image.

You need to diasble CDF protection or to expose images from another endpoint.

https://stackoverflow.com/questions/66140398/how-to-get-asset-from-a-cloudflare-ddos-protected-url

**Comment by SebeeDev** [comment]
In my honest opinion we should create JSON API which returns recent news , so you can easily fetch any details you need.

**Comment by maddoctor1905** [comment]
This is not an issue about the data itself (stored in the database). It is about accessing images protected by cloudflare :) . If the API serves the images the problem would be solved. The quick fix would be to disable cloudflare ddos proctection. An another one would be to move images from the website and to store them somewhere else.

**Comment by SebeeDev** [comment]
I changed some CloudFlare settings and everything should be alright.
PS.: I wanted to create API so you can get titles of news articles in an easy way.

**Comment by maddoctor1905** [comment]
Okay thanks. I can access images.

**Comment by Azword** [comment]
Fixed in launcher@1.1.0
Fixed in backend@1.0.6
